### ISSUE TITLE
[joss-review] An example application & figure in the paper would help quickly assessing the core functionalities of the library

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#1]
...ideally with a real robot.

**Comment by CoreRobotics** [comment]
Unfortunately, we can't put any figures of our ongoing projects in the paper due to confidentiality issues, but I will update the paper.md with a description of a motivating application.

**Comment by CoreRobotics** [comment]
The paper.md has been updated.

**Comment by bmagyar** [comment]
Where? Please reference a pull request. I can't seem to find it on master or in the joss-issues branch.

**Comment by CoreRobotics** [comment]
Like the others, since I've already merged the changes back into the master, unfortunately I can't put in a pull request. I'll reference the commits so you can still see how we addressed the issues. I'll make sure for the remaining work, I keep it in our joss_issues branch so I can make a pull request and be better at collaboration.

I've updated the paper.md with a paragraph about an example application.  Although now I'm thinking that it would be good to include a couple example .cpp files that demonstrate how to use our core classes since we are changing the test scripts to use GTest, addressing: https://github.com/CoreRobotics/CoreRobotics/issues/2

See: https://github.com/CoreRobotics/CoreRobotics/commit/16b8072b5419fb2813ccc78e56fea7336ecc1c80

**Comment by bmagyar** [comment]
Good idea on adding examples!
You could also spice up the tests with comments that explain some logic, that also helps people wanting to use the library.

**Comment by CoreRobotics** [comment]
Created a pull request at [https://github.com/CoreRobotics/CoreRobotics/pull/8](https://github.com/CoreRobotics/CoreRobotics/pull/8).

The original "tests" were more of examples with comments on how to use the classes.  These have been moved to an /examples folder and are individually compiled for brevity. See commit: [https://github.com/CoreRobotics/CoreRobotics/pull/8/commits/3a482c39fa1ea9587051f9734c6378b4372b06f4](https://github.com/CoreRobotics/CoreRobotics/pull/8/commits/3a482c39fa1ea9587051f9734c6378b4372b06f4)

**Comment by bmagyar** [comment]
:+1:
