### ISSUE TITLE
[joss-review] Shipping custom version of boost and Eigen?

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#3]
While this seems to make life simpler at first, these dependencies should be installed separately. 

I am unfamiliar with how deployment goes on Windows systems but both Linux and OSX has package managers where these dependencies can be grabbed from. Dragging around copies of someone else's software is not too elegant. The current solution locks one in with the specific version of boost which if used in conjunction with other libraries (a ROS wrapper around a controller for instance)  collisions would be very likely to occur.

My proposed solution is to move the external dependencies to a different repository which would only be downloaded if the person is on Windows, Linux and OSX systems can use the system default (apt or brew installated) versions of these libraries.

**Comment by CoreRobotics** [comment]
Like the others, since I've already merged the changes back into the master, unfortunately I can't put in a pull request. I'll reference the commits so you can still see how we addressed the issues. I'll make sure for the remaining work, I keep it in our joss_issues branch so I can make a pull request and be better at collaboration.

Good call on this one.  In order to address this issue, we removed the external folder containing eigen and boost and moved them over to a different repository (https://gitlab.com/powan/CRexternal).  To check for eigen and boost, we updated CMakeLists.txt to automatically find the needed packages.  We also added eigen and boost to the docker image used as our CI runner.  Instructions were adjusted for the new approach.

See: https://github.com/CoreRobotics/CoreRobotics/commit/f7bcef38aa93e6e896c73e08f682baaf60eb941d https://github.com/CoreRobotics/CoreRobotics/commit/32d2681365521b055541a38ee813f8f4696a9baa

**Comment by bmagyar** [comment]
:+1:
