### ISSUE TITLE
[joss-review] Please don't define PI again

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#4]
https://github.com/CoreRobotics/CoreRobotics/blob/master/src/math/CRMath.hpp#L98

https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

**Comment by CoreRobotics** [comment]
This is updated in the joss_issues branch and will be pushed to master shortly.

**Comment by bmagyar** [comment]
Reference it please in a pull request. These issues are to keep track of what got done, don't close them unless you've actually merged the solutions.

**Comment by CoreRobotics** [comment]
Sorry for the confusion on issues, we've been using Gitlab, the Github page is a mirror.  I'll use the pull requests feature for the issues.

**Comment by CoreRobotics** [comment]
Like the others, since I've already merged the changes back into the master, unfortunately I can't put in a pull request. I'll reference the commits so you can still see how we addressed the issues. I'll make sure for the remaining work, I keep it in our joss_issues branch so I can make a pull request and be better at collaboration.

In order to address this issue, we removed all references in the classes and tests to CR_PI.  When a value for pi is needed, we use M_PI from the standard math library constants.  This involved a couple changes to the python and matlab wrappers as well in later commits for CI improvement

See: https://github.com/CoreRobotics/CoreRobotics/commit/058af7bdd931c8f025860ebfb2a3422b6aa349a1 https://github.com/CoreRobotics/CoreRobotics/commit/774c5a1c5fa022535a6df67dc5073e960429822c https://github.com/CoreRobotics/CoreRobotics/commit/ccb3dfd0b2703060623c7f69fd5a8b5cdbbcbcdd

**Comment by bmagyar** [comment]
Big thumbs up ! :+1:
